import { User, Role, Category, Subcategory, Item, ItemImage, Settings } from './types';

// Helper to generate dates
const daysAgo = (days: number) => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date;
};

// Available Permissions
export const AVAILABLE_PERMISSIONS = [
  'view_products',
  'create_products',
  'edit_products',
  'delete_products',
  'view_catalogues',
  'create_catalogues',
  'edit_catalogues',
  'delete_catalogues',
  'view_categories',
  'create_categories',
  'edit_categories',
  'delete_categories',
  'view_users',
  'create_users',
  'edit_users',
  'delete_users',
  'view_settings',
  'edit_settings',
  'generate_pdfs',
  'bulk_upload',
];

// Mock Roles
export const mockRoles: Role[] = [
  {
    id: 'role1',
    name: 'Administrator',
    permissions: AVAILABLE_PERMISSIONS,
    createdAt: daysAgo(365),
    updatedAt: daysAgo(365),
  },
  {
    id: 'role2',
    name: 'Manager',
    permissions: [
      'view_products',
      'create_products',
      'edit_products',
      'view_catalogues',
      'create_catalogues',
      'edit_catalogues',
      'view_categories',
      'generate_pdfs',
    ],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(365),
  },
  {
    id: 'role3',
    name: 'Client',
    permissions: ['view_products', 'view_catalogues'],
    createdAt: daysAgo(365),
    updatedAt: daysAgo(365),
  },
];

// Mock Users
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Admin User',
    email: 'admin@corporategifts.com',
    roleId: 'role1',
    permissions: [],
    status: 'active',
    createdAt: daysAgo(180),
    updatedAt: daysAgo(1),
  },
  {
    id: '2',
    name: 'John Manager',
    email: 'john@example.com',
    roleId: 'role2',
    permissions: [],
    status: 'active',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(5),
  },
  {
    id: '3',
    name: 'Client ABC Corp',
    email: 'contact@abccorp.com',
    roleId: 'role3',
    permissions: [],
    status: 'active',
    createdAt: daysAgo(30),
    updatedAt: daysAgo(2),
  },
];

// Mock Categories
export const mockCategories: Category[] = [
  {
    id: 'cat1',
    name: 'Office Essentials',
    description: 'Essential office supplies and accessories',
    status: 'active',
    createdAt: daysAgo(150),
    updatedAt: daysAgo(10),
  },
  {
    id: 'cat2',
    name: 'Premium Gifts',
    description: 'High-end premium corporate gifts',
    status: 'active',
    createdAt: daysAgo(140),
    updatedAt: daysAgo(15),
  },
  {
    id: 'cat3',
    name: 'Tech Gifts',
    description: 'Technology and electronic gifts',
    status: 'active',
    createdAt: daysAgo(130),
    updatedAt: daysAgo(20),
  },
  {
    id: 'cat4',
    name: 'Eco-Friendly Gifts',
    description: 'Sustainable and eco-friendly products',
    status: 'active',
    createdAt: daysAgo(120),
    updatedAt: daysAgo(25),
  },
  {
    id: 'cat5',
    name: 'Apparel',
    description: 'Corporate clothing and accessories',
    status: 'active',
    createdAt: daysAgo(110),
    updatedAt: daysAgo(30),
  },
  {
    id: 'cat6',
    name: 'Drinkware',
    description: 'Bottles, mugs, and tumblers',
    status: 'active',
    createdAt: daysAgo(100),
    updatedAt: daysAgo(35),
  },
  {
    id: 'cat7',
    name: 'Bags',
    description: 'Bags, backpacks, and travel accessories',
    status: 'active',
    createdAt: daysAgo(90),
    updatedAt: daysAgo(40),
  },
  {
    id: 'cat8',
    name: 'Stationery',
    description: 'Writing instruments and paper products',
    status: 'active',
    createdAt: daysAgo(80),
    updatedAt: daysAgo(45),
  },
];

// Mock Subcategories
export const mockSubcategories: Subcategory[] = [
  // Tech Gifts
  { id: 'sub1', categoryId: 'cat3', name: 'Power Banks', description: 'Portable charging solutions', status: 'active', createdAt: daysAgo(130), updatedAt: daysAgo(20) },
  { id: 'sub2', categoryId: 'cat3', name: 'Bluetooth Speakers', description: 'Wireless audio devices', status: 'active', createdAt: daysAgo(130), updatedAt: daysAgo(20) },
  { id: 'sub3', categoryId: 'cat3', name: 'Wireless Chargers', description: 'Qi wireless charging pads', status: 'active', createdAt: daysAgo(130), updatedAt: daysAgo(20) },
  { id: 'sub4', categoryId: 'cat3', name: 'USB Drives', description: 'Flash storage devices', status: 'active', createdAt: daysAgo(130), updatedAt: daysAgo(20) },
  { id: 'sub5', categoryId: 'cat3', name: 'Headphones', description: 'Audio listening devices', status: 'active', createdAt: daysAgo(130), updatedAt: daysAgo(20) },

  // Drinkware
  { id: 'sub6', categoryId: 'cat6', name: 'Bottles', description: 'Water bottles and flasks', status: 'active', createdAt: daysAgo(100), updatedAt: daysAgo(35) },
  { id: 'sub7', categoryId: 'cat6', name: 'Mugs', description: 'Coffee and tea mugs', status: 'active', createdAt: daysAgo(100), updatedAt: daysAgo(35) },
  { id: 'sub8', categoryId: 'cat6', name: 'Tumblers', description: 'Insulated tumblers', status: 'active', createdAt: daysAgo(100), updatedAt: daysAgo(35) },

  // Office Essentials
  { id: 'sub9', categoryId: 'cat1', name: 'Desk Accessories', description: 'Organizers and desk tools', status: 'active', createdAt: daysAgo(150), updatedAt: daysAgo(10) },
  { id: 'sub10', categoryId: 'cat1', name: 'Notebooks', description: 'Writing notebooks and journals', status: 'active', createdAt: daysAgo(150), updatedAt: daysAgo(10) },

  // Premium Gifts
  { id: 'sub11', categoryId: 'cat2', name: 'Luxury Pens', description: 'Premium writing instruments', status: 'active', createdAt: daysAgo(140), updatedAt: daysAgo(15) },
  { id: 'sub12', categoryId: 'cat2', name: 'Executive Gifts', description: 'High-end executive items', status: 'active', createdAt: daysAgo(140), updatedAt: daysAgo(15) },
  { id: 'sub13', categoryId: 'cat2', name: 'Watches', description: 'Corporate watches', status: 'active', createdAt: daysAgo(140), updatedAt: daysAgo(15) },

  // Bags
  { id: 'sub14', categoryId: 'cat7', name: 'Backpacks', description: 'Business backpacks', status: 'active', createdAt: daysAgo(90), updatedAt: daysAgo(40) },
  { id: 'sub15', categoryId: 'cat7', name: 'Laptop Bags', description: 'Professional laptop carriers', status: 'active', createdAt: daysAgo(90), updatedAt: daysAgo(40) },
];

// Product images (using Unsplash URLs)
const productImages = [
  'https://images.unsplash.com/3/www.madebyvadim.com.jpg?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1544377208-215a63786183?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyfHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1543253454-467bd6c1e154?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwzfHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1637868796504-32f45a96d5a0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw0fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1607083206139-7c5b07e66ac3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw1fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1694481901573-a970f982ac5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw2fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1671749999622-4087a86868cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw3fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1620141609488-b7a3da6e7cc3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw4fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1560183978-7b9d5d56382b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHw5fHxjb3Jwb3JhdGUlMjBnaWZ0cyUyMGJ1c2luZXNzJTIwYWNjZXNzb3JpZXN8ZW58MXx8fHwxNzc5MDM5NzUyfDA&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1613579992589-02487515f4d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxMHx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1560671582-7668ca55fdc8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxMXx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1620233376721-aad5c8808e32?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxMnx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1592348345559-ea5dad110fdb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxM3x8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1619747480497-4facc7f441fa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxNHx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1642418714495-87fcca453f70?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxNXx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1454587399083-b11b22f48fb6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxNnx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1637627201100-b5e4ea3afe5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxN3x8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1621879675198-cbfcead7fe6e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxOHx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1582993467771-54d2ae110087?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxOXx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
  'https://images.unsplash.com/photo-1656695537545-cfcb911d647a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwyMHx8Y29ycG9yYXRlJTIwZ2lmdHMlMjBidXNpbmVzcyUyMGFjY2Vzc29yaWVzfGVufDF8fHx8MTc3OTAzOTc1Mnww&ixlib=rb-4.1.0&q=80&w=400',
];

// Mock Items
export const mockItems: Item[] = [
  {
    id: 'item1',
    categoryId: 'cat3',
    subcategoryId: 'sub5',
    itemName: 'Premium Wireless Headphones',
    itemCode: 'TWG-HP-001',
    shortDescription: 'Noise-cancelling wireless headphones with premium sound quality',
    detailedDescription: 'Professional grade wireless headphones with active noise cancellation, 30-hour battery life, and premium leather cushions. Perfect for corporate professionals.',
    price: 149.99,
    minimumOrderQuantity: 50,
    colors: 'Black, Silver, Navy',
    material: 'Premium plastic and leather',
    dimensions: '8" x 7" x 3"',
    brandingOptions: 'Logo engraving on ear cups, Custom packaging available',
    tags: ['tech', 'audio', 'premium', 'wireless'],
    status: 'active',
    images: [
      { id: 'img1-1', itemId: 'item1', imageUrl: productImages[0], imageOrder: 1, isPrimary: true, createdAt: daysAgo(10), updatedAt: daysAgo(10) },
      { id: 'img1-2', itemId: 'item1', imageUrl: productImages[1], imageOrder: 2, isPrimary: false, createdAt: daysAgo(10), updatedAt: daysAgo(10) },
    ],
    createdAt: daysAgo(60),
    updatedAt: daysAgo(5),
  },
  {
    id: 'item2',
    categoryId: 'cat2',
    subcategoryId: 'sub13',
    itemName: 'Executive Watch Gift Set',
    itemCode: 'PWG-WT-002',
    shortDescription: 'Elegant executive watch with premium packaging',
    detailedDescription: 'Sophisticated timepiece with stainless steel band and sapphire crystal. Comes in luxury gift box, perfect for executive gifting.',
    price: 299.99,
    minimumOrderQuantity: 25,
    colors: 'Silver, Gold, Black',
    material: 'Stainless steel, Sapphire crystal',
    dimensions: 'Watch diameter: 42mm',
    brandingOptions: 'Laser engraving on case back, Custom gift box',
    tags: ['premium', 'executive', 'luxury', 'watch'],
    status: 'active',
    images: [
      { id: 'img2-1', itemId: 'item2', imageUrl: productImages[2], imageOrder: 1, isPrimary: true, createdAt: daysAgo(55), updatedAt: daysAgo(55) },
      { id: 'img2-2', itemId: 'item2', imageUrl: productImages[3], imageOrder: 2, isPrimary: false, createdAt: daysAgo(55), updatedAt: daysAgo(55) },
    ],
    createdAt: daysAgo(55),
    updatedAt: daysAgo(3),
  },
  {
    id: 'item3',
    categoryId: 'cat2',
    subcategoryId: 'sub11',
    itemName: 'Luxury Leather Wallet',
    itemCode: 'PWG-WL-003',
    shortDescription: 'Premium leather bifold wallet with RFID protection',
    detailedDescription: 'Handcrafted genuine leather wallet with RFID blocking technology. Features multiple card slots and bill compartments.',
    price: 79.99,
    minimumOrderQuantity: 100,
    colors: 'Brown, Black, Tan',
    material: 'Genuine leather',
    dimensions: '4.5" x 3.5" x 0.75"',
    brandingOptions: 'Embossed logo, Custom gift packaging',
    tags: ['leather', 'premium', 'accessories', 'wallet'],
    status: 'active',
    images: [
      { id: 'img3-1', itemId: 'item3', imageUrl: productImages[8], imageOrder: 1, isPrimary: true, createdAt: daysAgo(50), updatedAt: daysAgo(50) },
    ],
    createdAt: daysAgo(50),
    updatedAt: daysAgo(7),
  },
  {
    id: 'item4',
    categoryId: 'cat3',
    subcategoryId: 'sub1',
    itemName: 'High-Capacity Power Bank',
    itemCode: 'TWG-PB-004',
    shortDescription: '20000mAh portable charger with dual USB ports',
    detailedDescription: 'Fast-charging power bank with LED display showing remaining battery. Compatible with all devices.',
    price: 45.99,
    minimumOrderQuantity: 100,
    colors: 'Black, White, Blue',
    material: 'Aluminum alloy',
    dimensions: '6" x 3" x 0.8"',
    brandingOptions: 'Laser engraving, Full color printing',
    tags: ['tech', 'charging', 'portable', 'electronics'],
    status: 'active',
    images: [
      { id: 'img4-1', itemId: 'item4', imageUrl: productImages[7], imageOrder: 1, isPrimary: true, createdAt: daysAgo(45), updatedAt: daysAgo(45) },
      { id: 'img4-2', itemId: 'item4', imageUrl: productImages[10], imageOrder: 2, isPrimary: false, createdAt: daysAgo(45), updatedAt: daysAgo(45) },
    ],
    createdAt: daysAgo(45),
    updatedAt: daysAgo(2),
  },
  {
    id: 'item5',
    categoryId: 'cat1',
    subcategoryId: 'sub9',
    itemName: 'Executive Desk Organizer Set',
    itemCode: 'OEG-DO-005',
    shortDescription: 'Premium wooden desk accessories set',
    detailedDescription: 'Complete desk organization set including pen holder, card holder, and memo pad. Crafted from sustainable wood.',
    price: 89.99,
    minimumOrderQuantity: 50,
    colors: 'Walnut, Oak, Mahogany',
    material: 'Sustainable hardwood',
    dimensions: '12" x 8" x 4"',
    brandingOptions: 'Laser engraving on each piece',
    tags: ['office', 'desk', 'organization', 'wood'],
    status: 'active',
    images: [
      { id: 'img5-1', itemId: 'item5', imageUrl: productImages[11], imageOrder: 1, isPrimary: true, createdAt: daysAgo(40), updatedAt: daysAgo(40) },
      { id: 'img5-2', itemId: 'item5', imageUrl: productImages[14], imageOrder: 2, isPrimary: false, createdAt: daysAgo(40), updatedAt: daysAgo(40) },
    ],
    createdAt: daysAgo(40),
    updatedAt: daysAgo(8),
  },
  {
    id: 'item6',
    categoryId: 'cat2',
    subcategoryId: 'sub11',
    itemName: 'Premium Pen & Pencil Set',
    itemCode: 'PWG-PP-006',
    shortDescription: 'Executive writing instruments in luxury gift box',
    detailedDescription: 'Matching pen and pencil set with rhodium plating and elegant design. Perfect for executive gifting.',
    price: 129.99,
    minimumOrderQuantity: 50,
    colors: 'Silver, Gold, Rose Gold',
    material: 'Metal with rhodium plating',
    dimensions: '6" length each',
    brandingOptions: 'Laser engraving on clip or barrel',
    tags: ['premium', 'writing', 'executive', 'luxury'],
    status: 'active',
    images: [
      { id: 'img6-1', itemId: 'item6', imageUrl: productImages[12], imageOrder: 1, isPrimary: true, createdAt: daysAgo(35), updatedAt: daysAgo(35) },
      { id: 'img6-2', itemId: 'item6', imageUrl: productImages[16], imageOrder: 2, isPrimary: false, createdAt: daysAgo(35), updatedAt: daysAgo(35) },
    ],
    createdAt: daysAgo(35),
    updatedAt: daysAgo(4),
  },
  {
    id: 'item7',
    categoryId: 'cat3',
    subcategoryId: 'sub3',
    itemName: 'Wireless Charging Pad',
    itemCode: 'TWG-WC-007',
    shortDescription: 'Fast wireless charging station for all Qi-enabled devices',
    detailedDescription: 'Sleek wireless charging pad with non-slip surface and LED indicator. 15W fast charging support.',
    price: 35.99,
    minimumOrderQuantity: 200,
    colors: 'Black, White',
    material: 'Tempered glass and aluminum',
    dimensions: '4" diameter x 0.5" height',
    brandingOptions: 'Full color printing, Laser engraving',
    tags: ['tech', 'wireless', 'charging', 'modern'],
    status: 'active',
    images: [
      { id: 'img7-1', itemId: 'item7', imageUrl: productImages[13], imageOrder: 1, isPrimary: true, createdAt: daysAgo(30), updatedAt: daysAgo(30) },
    ],
    createdAt: daysAgo(30),
    updatedAt: daysAgo(1),
  },
  {
    id: 'item8',
    categoryId: 'cat1',
    subcategoryId: 'sub10',
    itemName: 'Leather-Bound Journal',
    itemCode: 'OEG-JN-008',
    shortDescription: 'Premium leather journal with 200 pages',
    detailedDescription: 'Handcrafted leather journal with high-quality paper, bookmark ribbon, and elastic closure.',
    price: 42.99,
    minimumOrderQuantity: 100,
    colors: 'Brown, Black, Burgundy',
    material: 'Genuine leather, Acid-free paper',
    dimensions: '8.5" x 5.5"',
    brandingOptions: 'Embossed logo on cover, Custom packaging',
    tags: ['notebook', 'journal', 'leather', 'writing'],
    status: 'active',
    images: [
      { id: 'img8-1', itemId: 'item8', imageUrl: productImages[15], imageOrder: 1, isPrimary: true, createdAt: daysAgo(25), updatedAt: daysAgo(25) },
    ],
    createdAt: daysAgo(25),
    updatedAt: daysAgo(6),
  },
  {
    id: 'item9',
    categoryId: 'cat2',
    subcategoryId: 'sub12',
    itemName: 'Premium Gift Box Collection',
    itemCode: 'PWG-GB-009',
    shortDescription: 'Luxury gift box with assorted premium items',
    detailedDescription: 'Curated gift box containing premium pen, leather cardholder, and branded accessories.',
    price: 199.99,
    minimumOrderQuantity: 25,
    colors: 'Custom branding',
    material: 'Various premium materials',
    dimensions: '12" x 10" x 4" box',
    brandingOptions: 'Custom branded box, Individual item branding',
    tags: ['premium', 'gift-set', 'luxury', 'collection'],
    status: 'active',
    images: [
      { id: 'img9-1', itemId: 'item9', imageUrl: productImages[4], imageOrder: 1, isPrimary: true, createdAt: daysAgo(20), updatedAt: daysAgo(20) },
      { id: 'img9-2', itemId: 'item9', imageUrl: productImages[5], imageOrder: 2, isPrimary: false, createdAt: daysAgo(20), updatedAt: daysAgo(20) },
      { id: 'img9-3', itemId: 'item9', imageUrl: productImages[6], imageOrder: 3, isPrimary: false, createdAt: daysAgo(20), updatedAt: daysAgo(20) },
    ],
    createdAt: daysAgo(20),
    updatedAt: daysAgo(1),
  },
  {
    id: 'item10',
    categoryId: 'cat3',
    subcategoryId: 'sub4',
    itemName: 'Custom USB Flash Drive',
    itemCode: 'TWG-USB-010',
    shortDescription: '32GB USB 3.0 flash drive with custom branding',
    detailedDescription: 'High-speed USB 3.0 drive with keychain attachment. Available in multiple styles and capacities.',
    price: 18.99,
    minimumOrderQuantity: 500,
    colors: 'Black, Silver, Blue, Red',
    material: 'Metal or plastic casing',
    dimensions: '2.5" x 0.75" x 0.25"',
    brandingOptions: 'Full color printing, Laser engraving, Custom shape available',
    tags: ['tech', 'storage', 'usb', 'data'],
    status: 'active',
    images: [
      { id: 'img10-1', itemId: 'item10', imageUrl: productImages[9], imageOrder: 1, isPrimary: true, createdAt: daysAgo(15), updatedAt: daysAgo(15) },
    ],
    createdAt: daysAgo(15),
    updatedAt: daysAgo(2),
  },
  {
    id: 'item11',
    categoryId: 'cat1',
    subcategoryId: 'sub9',
    itemName: 'Desk Accessory Bundle',
    itemCode: 'OEG-DA-011',
    shortDescription: 'Complete office desk accessories set',
    detailedDescription: 'Everything needed for a professional workspace: stapler, tape dispenser, scissors, pen holder, and more.',
    price: 54.99,
    minimumOrderQuantity: 75,
    material: 'Mixed materials',
    dimensions: 'Bundle set',
    brandingOptions: 'Logo on selected items',
    tags: ['office', 'bundle', 'desk', 'accessories'],
    status: 'active',
    images: [
      { id: 'img11-1', itemId: 'item11', imageUrl: productImages[18], imageOrder: 1, isPrimary: true, createdAt: daysAgo(12), updatedAt: daysAgo(12) },
    ],
    createdAt: daysAgo(12),
    updatedAt: daysAgo(3),
  },
  {
    id: 'item12',
    categoryId: 'cat2',
    subcategoryId: 'sub12',
    itemName: 'Executive Key Holder',
    itemCode: 'PWG-KH-012',
    shortDescription: 'Premium leather key organizer with gift packaging',
    detailedDescription: 'Elegant key holder crafted from premium leather. Compact design holds 6-8 keys securely.',
    price: 34.99,
    minimumOrderQuantity: 150,
    colors: 'Black, Brown, Navy',
    material: 'Genuine leather, Stainless steel hardware',
    dimensions: '4" x 1.5" x 0.75"',
    brandingOptions: 'Embossed logo, Custom gift box',
    tags: ['leather', 'premium', 'accessories', 'keys'],
    status: 'active',
    images: [
      { id: 'img12-1', itemId: 'item12', imageUrl: productImages[17], imageOrder: 1, isPrimary: true, createdAt: daysAgo(8), updatedAt: daysAgo(8) },
    ],
    createdAt: daysAgo(8),
    updatedAt: daysAgo(1),
  },
];

// Mock Settings
export const mockSettings: Settings = {
  id: '1',
  companyName: 'Premier Corporate Gifts',
  contactEmail: 'sales@premiercorporategifts.com',
  contactPhone: '+1 (555) 123-4567',
  address: '123 Business Park, Suite 200, New York, NY 10001',
  defaultPdfHeader: 'Premier Corporate Gifts - Quality Products for Your Business',
  defaultPdfFooter: 'Contact us: sales@premiercorporategifts.com | +1 (555) 123-4567',
  defaultThemeColor: '#2563eb',
  defaultCurrency: 'USD',
  createdAt: daysAgo(365),
  updatedAt: daysAgo(30),
};

// localStorage keys
export const STORAGE_KEYS = {
  USERS: 'cgm_users',
  ROLES: 'cgm_roles',
  CATEGORIES: 'cgm_categories',
  SUBCATEGORIES: 'cgm_subcategories',
  ITEMS: 'cgm_items',
  SETTINGS: 'cgm_settings',
  CURRENT_USER: 'cgm_current_user',
  AUTH_TOKEN: 'cgm_auth_token',
  CATALOGUES: 'cgm_catalogues',
  PDFS: 'cgm_pdfs',
} as const;

// Initialize localStorage with mock data
export const initializeMockData = () => {
  if (!localStorage.getItem(STORAGE_KEYS.ROLES)) {
    localStorage.setItem(STORAGE_KEYS.ROLES, JSON.stringify(mockRoles));
  }
  if (!localStorage.getItem(STORAGE_KEYS.SETTINGS)) {
    localStorage.setItem(STORAGE_KEYS.SETTINGS, JSON.stringify(mockSettings));
  }
};
